version: '3.8'
services: 
  streamlit:
        build: ./app
        ports:
          - "8501:8501"
        environment:
          - OPENAI_API_KEY=${OPENAI_API_KEY}
        volumes:
          - ./app:/opt/app
