''' In this file we fetch the data from the API. '''
import time
import asyncio
import httpx
import json

all_ch_layers = [
    "ch.agroscope.feuchtflaechenpotential-kulturlandschaft",
    "ch.are.agglomerationsverkehr",
    "ch.are.alpenkonvention",
    "ch.are.bauzonen",
    "ch.are.belastung-gueterverkehr-bahn",
    "ch.are.belastung-gueterverkehr-strasse",
    "ch.are.belastung-personenverkehr-bahn",
    "ch.are.belastung-personenverkehr-bahn_zukunft",
    "ch.are.belastung-personenverkehr-strasse",
    "ch.are.belastung-personenverkehr-strasse_zukunft",
    "ch.are.erreichbarkeit-miv",
    "ch.are.erreichbarkeit-oev",
    "ch.are.gemeindetypen",
    "ch.are.gueteklassen_oev",
    "ch.are.landschaftstypen",
    "ch.are.reisezeit-agglomerationen-miv",
    "ch.are.reisezeit-agglomerationen-oev",
    "ch.are.reisezeit-miv",
    "ch.are.reisezeit-oev",
    "ch.are.windenergie-bundesinteressen",
    "ch.are.wohnungsinventar-zweitwohnungsanteil",
    "ch.astra.baulinien-nationalstrassen",
    "ch.astra.hauptstrassennetz",
    "ch.astra.ivs-gelaendekarte",
    "ch.astra.ivs-nat",
    "ch.astra.ivs-nat-verlaeufe",
    "ch.astra.ivs-nat_abgrenzungen",
    "ch.astra.ivs-nat_wegbegleiter",
    "ch.astra.ivs-reg_loc",
    "ch.astra.mountainbikeland",
    "ch.astra.mountainbikeland-sperrungen_umleitungen",
    "ch.astra.nationalstrassenachsen",
    "ch.astra.sachplan-infrastruktur-strasse_kraft",
    "ch.astra.schwerverunfallte-kanton_alkohol",
    "ch.astra.schwerverunfallte-kanton_geschwindigkeit",
    "ch.astra.schwerverunfallte-kanton_jahresvergleich",
    "ch.astra.schwerverunfallte-kanton_pro_einwohner",
    "ch.astra.skatingland",
    "ch.astra.skatingland-sperrungen_umleitungen",
    "ch.astra.strassenverkehrszaehlung-uebergeordnet",
    "ch.astra.unfaelle-personenschaeden_alle",
    "ch.astra.unfaelle-personenschaeden_fahrraeder",
    "ch.astra.unfaelle-personenschaeden_fussgaenger",
    "ch.astra.unfaelle-personenschaeden_getoetete",
    "ch.astra.unfaelle-personenschaeden_motorraeder",
    "ch.astra.veloland",
    "ch.astra.veloland-sperrungen_umleitungen",
    "ch.astra.wanderland",
    "ch.astra.wanderland-sperrungen_umleitungen",
    "ch.babs.kulturgueter",
    "ch.bafu.alpweiden-herdenschutzhunde",
    "ch.bafu.amphibienwanderung-verkehrskonflikte",
    "ch.bafu.aquaprotect_050",
    "ch.bafu.aquaprotect_100",
    "ch.bafu.aquaprotect_250",
    "ch.bafu.aquaprotect_500",
    "ch.bafu.auen-ausserhalb_bundesinventar",
    "ch.bafu.auen-ausserhalb_bundesinventar_alpin",
    "ch.bafu.auen-vegetationskarten",
    "ch.bafu.biogeographische_regionen",
    "ch.bafu.bundesinventare-amphibien",
    "ch.bafu.bundesinventare-amphibien_anhang4",
    "ch.bafu.bundesinventare-amphibien_wanderobjekte",
    "ch.bafu.bundesinventare-auen",
    "ch.bafu.bundesinventare-auen_anhang2",
    "ch.bafu.bundesinventare-auen_vegetation_alpin",
    "ch.bafu.bundesinventare-bln",
    "ch.bafu.bundesinventare-flachmoore",
    "ch.bafu.bundesinventare-hochmoore",
    "ch.bafu.bundesinventare-jagdbanngebiete",
    "ch.bafu.bundesinventare-moorlandschaften",
    "ch.bafu.bundesinventare-trockenwiesen_trockenweiden",
    "ch.bafu.bundesinventare-trockenwiesen_trockenweiden_anhang2",
    "ch.bafu.bundesinventare-vogelreservate",
    "ch.bafu.erosion-gruenland_bodenabtrag_apr",
    "ch.bafu.erosion-gruenland_bodenabtrag_aug",
    "ch.bafu.erosion-gruenland_bodenabtrag_dez",
    "ch.bafu.erosion-gruenland_bodenabtrag_feb",
    "ch.bafu.erosion-gruenland_bodenabtrag_jan",
    "ch.bafu.erosion-gruenland_bodenabtrag_jul",
    "ch.bafu.erosion-gruenland_bodenabtrag_jun",
    "ch.bafu.erosion-gruenland_bodenabtrag_mai",
    "ch.bafu.erosion-gruenland_bodenabtrag_mrz",
    "ch.bafu.erosion-gruenland_bodenabtrag_nov",
    "ch.bafu.erosion-gruenland_bodenabtrag_okt",
    "ch.bafu.erosion-gruenland_bodenabtrag_sep",
    "ch.bafu.fauna-steinbockkolonien",
    "ch.bafu.fauna-vernetzungsachsen_national",
    "ch.bafu.fauna-wildtierkorridor_national",
    "ch.bafu.fauna-wildtierpassagen",
    "ch.bafu.feststoffe-geschiebemessnetz",
    "ch.bafu.fischerei-aeschen_kernzonen",
    "ch.bafu.fischerei-aeschen_laichplaetze",
    "ch.bafu.fischerei-aeschen_larvenhabitate",
    "ch.bafu.fischerei-aeschen_verbreitungsgebiet",
    "ch.bafu.fischerei-krebspest",
    "ch.bafu.fischerei-nasenlaichplaetze",
    "ch.bafu.fischerei-proliferative_nierenkrankheit",
    "ch.bafu.flora-schwingrasen",
    "ch.bafu.flora-verbreitungskarten",
    "ch.bafu.flora-weltensutter_atlas",
    "ch.bafu.flussordnungszahlen-strahler",
    "ch.bafu.gefaehrdungskarte-oberflaechenabfluss",
    "ch.bafu.gefahren-basiskarte",
    "ch.bafu.gefahren-baugrundklassen",
    "ch.bafu.gefahren-gefaehrdungszonen",
    "ch.bafu.gefahren-historische_erdbeben",
    "ch.bafu.gefahren-spektral",
    "ch.bafu.gefahren-waldbrand_praeventionsmassnahmen_kantone",
    "ch.bafu.gefahren-waldbrand_warnung",
    "ch.bafu.geochemischer-bodenatlas_schweiz_arsen",
    "ch.bafu.geochemischer-bodenatlas_schweiz_cadmium",
    "ch.bafu.geochemischer-bodenatlas_schweiz_chrom",
    "ch.bafu.geochemischer-bodenatlas_schweiz_kupfer",
    "ch.bafu.geochemischer-bodenatlas_schweiz_nickel",
    "ch.bafu.geochemischer-bodenatlas_schweiz_uran",
    "ch.bafu.geochemischer-bodenatlas_schweiz_vanadium",
    "ch.bafu.geochemischer-bodenatlas_schweiz_zink",
    "ch.bafu.gewaesser-uferbestockung",
    "ch.bafu.gewaesser-uferbestockung_vegetation",
    "ch.bafu.gewaesserschutz-badewasserqualitaet",
    "ch.bafu.gewaesserschutz-biologischer_zustand_diatomeen",
    "ch.bafu.gewaesserschutz-biologischer_zustand_fische",
    "ch.bafu.gewaesserschutz-biologischer_zustand_makrophyten",
    "ch.bafu.gewaesserschutz-biologischer_zustand_makrozoobenthos",
    "ch.bafu.gewaesserschutz-chemischer_zustand_ammonium",
    "ch.bafu.gewaesserschutz-chemischer_zustand_doc",
    "ch.bafu.gewaesserschutz-chemischer_zustand_nitrat",
    "ch.bafu.gewaesserschutz-chemischer_zustand_nitrit",
    "ch.bafu.gewaesserschutz-chemischer_zustand_phosphat",
    "ch.bafu.gewaesserschutz-chemischer_zustand_phosphor_gesamt",
    "ch.bafu.gewaesserschutz-diffuse_eintraege_gesamt_phosphor",
    "ch.bafu.gewaesserschutz-diffuse_eintraege_phosphor",
    "ch.bafu.gewaesserschutz-diffuse_eintraege_stickstoff",
    "ch.bafu.gewaesserschutz-klaeranlagen_anteilq347",
    "ch.bafu.gewaesserschutz-klaeranlagen_ausbaugroesse",
    "ch.bafu.gewaesserschutz-klaeranlagen_reinigungstyp",
    "ch.bafu.grundwasserkoerper",
    "ch.bafu.hydrogeologie-markierversuche",
    "ch.bafu.hydrogeologie-uebersichtskarte",
    "ch.bafu.hydrogeologische-karte_100",
    "ch.bafu.hydrologie-daueruntersuchung_fliessgewaesser",
    "ch.bafu.hydrologie-gewaesserzustandsmessstationen",
    "ch.bafu.hydrologie-hintergrundkarte",
    "ch.bafu.hydrologie-hochwassergrenzwertpegel",
    "ch.bafu.hydrologie-hochwasserstatistik",
    "ch.bafu.hydrologie-hydromessstationen",
    "ch.bafu.hydrologie-niedrigwasserstatistik",
    "ch.bafu.hydrologie-q347",
    "ch.bafu.hydrologie-untersuchungsgebiete",
    "ch.bafu.hydrologie-untersuchungsgebiete_stationen",
    "ch.bafu.hydrologie-wassertemperaturmessstationen",
    "ch.bafu.hydrologischer-atlas_basisgebiete",
    "ch.bafu.hydrologischer-atlas_bilanzgebiete",
    "ch.bafu.hydrologischer-atlas_flussgebiete",
    "ch.bafu.hydrologischer-atlas_kantonale-messstationen",
    "ch.bafu.hydroweb-messstationen_gefahren",
    "ch.bafu.hydroweb-messstationen_grundwasser",
    "ch.bafu.hydroweb-messstationen_grundwassertemperatur",
    "ch.bafu.hydroweb-messstationen_grundwasserzustand",
    "ch.bafu.hydroweb-messstationen_temperatur",
    "ch.bafu.hydroweb-messstationen_vorhersage",
    "ch.bafu.hydroweb-messstationen_zustand",
    "ch.bafu.hydroweb-warnkarte_national",
    "ch.bafu.karst-ausdehnung_grundwasservorkommen",
    "ch.bafu.karst-einzugsgebiete",
    "ch.bafu.karst-einzugsgebietseinheiten",
    "ch.bafu.karst-quellen_schwinden",
    "ch.bafu.karst-unterirdische_fliesswege",
    "ch.bafu.klima-co2_ausstoss_gebaeude",
    "ch.bafu.laerm-bahnlaerm_nacht",
    "ch.bafu.laerm-bahnlaerm_tag",
    "ch.bafu.laerm-strassenlaerm_nacht",
    "ch.bafu.laerm-strassenlaerm_tag",
    "ch.bafu.landesforstinventar-kantone",
    "ch.bafu.landesforstinventar-produktionsregionen",
    "ch.bafu.landesforstinventar-schutzwaldregionen",
    "ch.bafu.landesforstinventar-vegetationshoehenmodell",
    "ch.bafu.landesforstinventar-vegetationshoehenmodell_relief",
    "ch.bafu.landesforstinventar-waldmischungsgrad",
    "ch.bafu.landesforstinventar-wirtschaftsregionen",
    "ch.bafu.lebensraumkarte-schweiz",
    "ch.bafu.luftreinhaltung-ammoniakkonzentration",
    "ch.bafu.luftreinhaltung-stickstoff_kritischer_eintrag",
    "ch.bafu.luftreinhaltung-stickstoffdeposition",
    "ch.bafu.mittlere-abfluesse",
    "ch.bafu.mittlere-abfluesse_zukunft",
    "ch.bafu.moose",
    "ch.bafu.nabelstationen",
    "ch.bafu.naqua-grundwasser_nitrat",
    "ch.bafu.naqua-grundwasser_voc",
    "ch.bafu.neophyten-amerikanische_kermesbeere",
    "ch.bafu.neophyten-amerikanischer_stinktierkohl",
    "ch.bafu.neophyten-armenische_brombeere",
    "ch.bafu.neophyten-aufrechtes_traubenkraut",
    "ch.bafu.neophyten-auslaeuferbildendes_fettkraut",
    "ch.bafu.neophyten-balfours_springkraut",
    "ch.bafu.neophyten-bastard_staudenknoeterich",
    "ch.bafu.neophyten-bastardindigo",
    "ch.bafu.neophyten-besen_radmelde",
    "ch.bafu.neophyten-blauglockenbaum",
    "ch.bafu.neophyten-brasilianisches_tausendblatt",
    "ch.bafu.neophyten-carolina_nachtschatten",
    "ch.bafu.neophyten-chinesische_samtpappel",
    "ch.bafu.neophyten-druesiges_springkraut",
    "ch.bafu.neophyten-einjaehriges_berufkraut",
    "ch.bafu.neophyten-essbare_kermesbeere",
    "ch.bafu.neophyten-essbares_zypergras",
    "ch.bafu.neophyten-essigbaum",
    "ch.bafu.neophyten-felsen_greiskraut",
    "ch.bafu.neophyten-fortunes_hanfpalme",
    "ch.bafu.neophyten-gestreiftes_suessgras",
    "ch.bafu.neophyten-gewoehnliche_jungfernrebe",
    "ch.bafu.neophyten-glattes_zackenschoetchen",
    "ch.bafu.neophyten-goetterbaum",
    "ch.bafu.neophyten-grossbluetiges_heusenkraut",
    "ch.bafu.neophyten-grosser_wassernabel",
    "ch.bafu.neophyten-haargurke",
    "ch.bafu.neophyten-henrys_geissblatt",
    "ch.bafu.neophyten-herbst_traubenkirsche",
    "ch.bafu.neophyten-igelgurke",
    "ch.bafu.neophyten-japanischer_staudenknoeterich",
    "ch.bafu.neophyten-japanisches_geissblatt",
    "ch.bafu.neophyten-kanadische_goldrute",
    "ch.bafu.neophyten-kanadische_wasserpest",
    "ch.bafu.neophyten-karolina_haarnixe",
    "ch.bafu.neophyten-kaukasus_fettkraut",
    "ch.bafu.neophyten-kirschlorbeer",
    "ch.bafu.neophyten-kletternder_giftsumach",
    "ch.bafu.neophyten-kopoubohne",
    "ch.bafu.neophyten-mahonie",
    "ch.bafu.neophyten-nadelkraut",
    "ch.bafu.neophyten-nuttalls_wasserpest",
    "ch.bafu.neophyten-portulak_heusenkraut",
    "ch.bafu.neophyten-riesenbaerenklau",
    "ch.bafu.neophyten-robinie",
    "ch.bafu.neophyten-runzelblaettriger_schneeball",
    "ch.bafu.neophyten-sachalin_staudenknoeterich",
    "ch.bafu.neophyten-schmetterlingsstrauch",
    "ch.bafu.neophyten-seidiger_hornstrauch",
    "ch.bafu.neophyten-spaetbluehende_goldrute",
    "ch.bafu.neophyten-suedafrikanisches_greiskraut",
    "ch.bafu.neophyten-syrische_seidenpflanze",
    "ch.bafu.neophyten-topinambur",
    "ch.bafu.neophyten-verlotscher_beifuss",
    "ch.bafu.neophyten-vielaehriger_knoeterich",
    "ch.bafu.neophyten-vielblaettrige_lupine",
    "ch.bafu.niederschlagserosivitaet-apr",
    "ch.bafu.niederschlagserosivitaet-aug",
    "ch.bafu.niederschlagserosivitaet-dez",
    "ch.bafu.niederschlagserosivitaet-feb",
    "ch.bafu.niederschlagserosivitaet-jan",
    "ch.bafu.niederschlagserosivitaet-jul",
    "ch.bafu.niederschlagserosivitaet-jun",
    "ch.bafu.niederschlagserosivitaet-mai",
    "ch.bafu.niederschlagserosivitaet-mrz",
    "ch.bafu.niederschlagserosivitaet-nov",
    "ch.bafu.niederschlagserosivitaet-okt",
    "ch.bafu.niederschlagserosivitaet-sep",
    "ch.bafu.oekomorphologie-f_abschnitte",
    "ch.bafu.oekomorphologie-f_abstuerze",
    "ch.bafu.oekomorphologie-f_bauwerke",
    "ch.bafu.permafrost",
    "ch.bafu.ren-extensive_landwirtschaftsgebiete",
    "ch.bafu.ren-feuchtgebiete",
    "ch.bafu.ren-fliessgewaesser_seen",
    "ch.bafu.ren-trockenstandorte",
    "ch.bafu.ren-wald",
    "ch.bafu.schutzgebiete-aulav_auen",
    "ch.bafu.schutzgebiete-aulav_jagdbanngebiete",
    "ch.bafu.schutzgebiete-aulav_moorlandschaften",
    "ch.bafu.schutzgebiete-aulav_uebrige",
    "ch.bafu.schutzgebiete-biosphaerenreservate",
    "ch.bafu.schutzgebiete-luftfahrt",
    "ch.bafu.schutzgebiete-paerke_nationaler_bedeutung",
    "ch.bafu.schutzgebiete-paerke_nationaler_bedeutung_perimeter",
    "ch.bafu.schutzgebiete-ramsar",
    "ch.bafu.schutzgebiete-schweizerischer_nationalpark",
    "ch.bafu.schutzgebiete-smaragd",
    "ch.bafu.silvaprotect-hangmuren",
    "ch.bafu.silvaprotect-lawinen",
    "ch.bafu.silvaprotect-murgang",
    "ch.bafu.silvaprotect-sturz",
    "ch.bafu.silvaprotect-uebersarung",
    "ch.bafu.strukturguete-hochrhein_linkesufer",
    "ch.bafu.strukturguete-hochrhein_linkesumfeld",
    "ch.bafu.strukturguete-hochrhein_rechtesufer",
    "ch.bafu.strukturguete-hochrhein_rechtesumfeld",
    "ch.bafu.strukturguete-hochrhein_sohle",
    "ch.bafu.sturm-boeenspitzen_100",
    "ch.bafu.sturm-boeenspitzen_30",
    "ch.bafu.sturm-boeenspitzen_300",
    "ch.bafu.sturm-boeenspitzen_50",
    "ch.bafu.sturm-staudruck_100",
    "ch.bafu.sturm-staudruck_30",
    "ch.bafu.sturm-staudruck_300",
    "ch.bafu.sturm-staudruck_50",
    "ch.bafu.swissprtr",
    "ch.bafu.tranquillity-gebiete",
    "ch.bafu.tranquillity-karte",
    "ch.bafu.typisierung-fliessgewaesser",
    "ch.bafu.unesco-weltnaturerbe",
    "ch.bafu.vec25-gewaessernetz_2000",
    "ch.bafu.vec25-seen",
    "ch.bafu.wald-foehnhaeufigkeit_jahr",
    "ch.bafu.wald-kontinentalitaet_jahr_1000m_1981_2010",
    "ch.bafu.wald-kontinentalitaet_juli_1000m_1981_2010",
    "ch.bafu.wald-lufttemperatur_juli_1961_1990",
    "ch.bafu.wald-lufttemperatur_juli_1981_2010",
    "ch.bafu.wald-lufttemperatur_juli_2085_gering",
    "ch.bafu.wald-lufttemperatur_juli_2085_maessig",
    "ch.bafu.wald-lufttemperatur_juli_2085_stark",
    "ch.bafu.wald-niederschlag_april_august_2085_gering",
    "ch.bafu.wald-niederschlag_april_august_2085_maessig",
    "ch.bafu.wald-niederschlag_april_august_2085_stark",
    "ch.bafu.wald-niederschlag_sommer_2085_gering",
    "ch.bafu.wald-niederschlag_sommer_2085_maessig",
    "ch.bafu.wald-niederschlag_sommer_2085_stark",
    "ch.bafu.wald-obere_waldgrenze",
    "ch.bafu.wald-relative_luftfeuchte_jahr_1981_2010",
    "ch.bafu.wald-relative_luftfeuchte_juli_1981_2010",
    "ch.bafu.wald-standortsregionen",
    "ch.bafu.wald-tannenareale",
    "ch.bafu.wald-vegetationshoehenstufen_1975",
    "ch.bafu.wald-vegetationshoehenstufen_2085_trocken",
    "ch.bafu.wald-vegetationshoehenstufen_2085_weniger_trocken",
    "ch.bafu.wald-wasserverfuegbarkeit_boden",
    "ch.bafu.wald-wasserverfuegbarkeit_pflanzen",
    "ch.bafu.waldreservate",
    "ch.bafu.waldschadenflaechen-lothar",
    "ch.bafu.waldschadenflaechen-vivian",
    "ch.bafu.wasser-entnahme",
    "ch.bafu.wasser-gebietsauslaesse",
    "ch.bafu.wasser-leitungen",
    "ch.bafu.wasser-rueckgabe",
    "ch.bafu.wasser-teileinzugsgebiete_2",
    "ch.bafu.wasser-teileinzugsgebiete_40",
    "ch.bafu.wasser-vorfluter",
    "ch.bafu.wasserbau-querprofilmarken",
    "ch.bafu.wasserbau-vermessungsstrecken",
    "ch.bafu.wrz-jagdbanngebiete_select",
    "ch.bafu.wrz-wildruhezonen_portal",
    "ch.bag.radioaktivitaet-atmosphaere",
    "ch.bag.radonkarte",
    "ch.bag.zecken-fsme-faelle",
    "ch.bag.zecken-fsme-impfung",
    "ch.bag.zeckenstichmodell",
    "ch.bak.bundesinventar-schuetzenswerte-ortsbilder",
    "ch.bak.bundesinventar-schuetzenswerte-ortsbilder_fotos",
    "ch.bak.halteplaetze-jenische_sinti_roma",
    "ch.bak.schutzgebiete-unesco_weltkulturerbe",
    "ch.bakom.anbieter-eigenes_festnetz",
    "ch.bakom.anschlussart-glasfaser",
    "ch.bakom.anschlussart-koaxialkabel",
    "ch.bakom.anschlussart-kupferdraht",
    "ch.bakom.downlink10",
    "ch.bakom.downlink100",
    "ch.bakom.downlink1000",
    "ch.bakom.downlink30",
    "ch.bakom.downlink300",
    "ch.bakom.downlink500",
    "ch.bakom.mobil-antennenstandorte-5g",
    "ch.bakom.mobil-antennenstandorte-gsm",
    "ch.bakom.mobil-antennenstandorte-lte",
    "ch.bakom.mobil-antennenstandorte-umts",
    "ch.bakom.mobilnetz-2g",
    "ch.bakom.mobilnetz-3g",
    "ch.bakom.mobilnetz-4g",
    "ch.bakom.mobilnetz-5g",
    "ch.bakom.notruf",
    "ch.bakom.notruf-112_festnetz",
    "ch.bakom.notruf-112_mobilnetz",
    "ch.bakom.notruf-112_satellit",
    "ch.bakom.notruf-112_zentral",
    "ch.bakom.notruf-117_festnetz",
    "ch.bakom.notruf-117_mobilnetz",
    "ch.bakom.notruf-117_zentral",
    "ch.bakom.notruf-118_festnetz",
    "ch.bakom.notruf-118_mobilnetz",
    "ch.bakom.notruf-118_zentral",
    "ch.bakom.notruf-143_festnetz",
    "ch.bakom.notruf-143_mobilnetz",
    "ch.bakom.notruf-143_zentral",
    "ch.bakom.notruf-144_festnetz",
    "ch.bakom.notruf-144_mobilnetz",
    "ch.bakom.notruf-144_zentral",
    "ch.bakom.notruf-145_festnetz",
    "ch.bakom.notruf-145_mobilnetz",
    "ch.bakom.notruf-145_zentral",
    "ch.bakom.notruf-147_festnetz",
    "ch.bakom.notruf-147_mobilnetz",
    "ch.bakom.notruf-147_zentral",
    "ch.bakom.radio-fernsehsender",
    "ch.bakom.uplink1",
    "ch.bakom.uplink10",
    "ch.bakom.uplink100",
    "ch.bakom.uplink1000",
    "ch.bakom.versorgungsgebiet-tv",
    "ch.bakom.versorgungsgebiet-ukw",
    "ch.baspo.nationales-sportanlagenkonzept",
    "ch.bav.anlagen-schienengueterverkehr",
    "ch.bav.betriebe-stoerfallverordnung_eisenbahnanlagen",
    "ch.bav.haltestellen-oev",
    "ch.bav.kataster-belasteter-standorte-oev",
    "ch.bav.laermbelastung-eisenbahn_effektive_immissionen_nacht",
    "ch.bav.laermbelastung-eisenbahn_effektive_immissionen_tag",
    "ch.bav.laermbelastung-eisenbahn_festgelegte_emissionen_nacht",
    "ch.bav.laermbelastung-eisenbahn_festgelegte_emissionen_tag",
    "ch.bav.laermbelastung-eisenbahn_laermschutzwaende",
    "ch.bav.laermbelastung-eisenbahn_tatsaechliche_emissionen_nacht",
    "ch.bav.laermbelastung-eisenbahn_tatsaechliche_emissionen_tag",
    "ch.bav.laermbelastung-eisenbahn_zulaessige_immissionen_nacht",
    "ch.bav.laermbelastung-eisenbahn_zulaessige_immissionen_tag",
    "ch.bav.lage-stoerfallverordnung_eisenbahnanlagen",
    "ch.bav.sachplan-infrastruktur-schiene_kraft",
    "ch.bav.sachplan-infrastruktur-schifffahrt_kraft",
    "ch.bav.schienennetz",
    "ch.bav.seilbahnen-bundeskonzession",
    "ch.bazl.bebaute-gebiete_luftfahrtrecht",
    "ch.bazl.einschraenkungen-drohnen",
    "ch.bazl.flugplaetze-heliports",
    "ch.bazl.gebirgslandeplaetze",
    "ch.bazl.intrinsisches-bodenrisiko_sora",
    "ch.bazl.kataster-belasteter-standorte-zivilflugplaetze",
    "ch.bazl.laermbelastungskataster-zivilflugplaetze_erste-nachtstunde",
    "ch.bazl.laermbelastungskataster-zivilflugplaetze_helikopter",
    "ch.bazl.laermbelastungskataster-zivilflugplaetze_helikopter-maximalpegel",
    "ch.bazl.laermbelastungskataster-zivilflugplaetze_klein-grossflugzeuge",
    "ch.bazl.laermbelastungskataster-zivilflugplaetze_kleinluftfahrzeuge",
    "ch.bazl.laermbelastungskataster-zivilflugplaetze_letzte-nachtstunde",
    "ch.bazl.laermbelastungskataster-zivilflugplaetze_militaer-gesamt",
    "ch.bazl.laermbelastungskataster-zivilflugplaetze_zweite-nachtstunde",
    "ch.bazl.landschaftsruhezonen",
    "ch.bazl.luftfahrthindernis",
    "ch.bazl.luftfahrthindernis-aenderungen",
    "ch.bazl.luftfahrthindernis-klein",
    "ch.bazl.luftraeume-fluginformationsgebiet",
    "ch.bazl.luftraeume-fluginformationszonen",
    "ch.bazl.luftraeume-kontrollbezirke",
    "ch.bazl.luftraeume-kontrollzonen",
    "ch.bazl.projektierungszonen-flughafenanlagen",
    "ch.bazl.sachplan-infrastruktur-luftfahrt_kraft",
    "ch.bazl.schutzgebiete-aulav_liechtenstein",
    "ch.bazl.sicherheitszonenplan",
    "ch.bazl.spitallandeplaetze",
    "ch.bfe.abgeltung-wasserkraftnutzung",
    "ch.bfe.biogasanlagen",
    "ch.bfe.biomasse-nicht-verholzt",
    "ch.bfe.biomasse-verholzt",
    "ch.bfe.elektrische-anlagen_ueber_36",
    "ch.bfe.elektrizitaetsproduktionsanlagen",
    "ch.bfe.energieberatungsstellen",
    "ch.bfe.energieforschung",
    "ch.bfe.energiestaedte",
    "ch.bfe.energiestaedte-2000watt-areale",
    "ch.bfe.erneuerbarheizen",
    "ch.bfe.erneuerbarheizen-mehrfamilienhaeuser",
    "ch.bfe.fernwaerme-angebot",
    "ch.bfe.fernwaerme-nachfrage_industrie",
    "ch.bfe.fernwaerme-nachfrage_wohn_dienstleistungsgebaeude",
    "ch.bfe.kehrichtverbrennungsanlagen",
    "ch.bfe.kernkraftwerke",
    "ch.bfe.kleinwasserkraftpotentiale",
    "ch.bfe.komo-projekte",
    "ch.bfe.ladestellen-elektromobilitaet",
    "ch.bfe.meteorologische-vereisung",
    "ch.bfe.minergiegebaeude",
    "ch.bfe.rohrleitungen-konsultationsbereiche",
    "ch.bfe.sachplan-geologie-tiefenlager",
    "ch.bfe.sachplan-uebertragungsleitungen_anhoerung",
    "ch.bfe.sachplan-uebertragungsleitungen_kraft",
    "ch.bfe.solarenergie-eignung-daecher",
    "ch.bfe.solarenergie-eignung-fassaden",
    "ch.bfe.statistik-wasserkraftanlagen",
    "ch.bfe.stauanlagen-bundesaufsicht",
    "ch.bfe.thermische-netze",
    "ch.bfe.waermepotential-gewaesser",
    "ch.bfe.windenergie-geschwindigkeit_h100",
    "ch.bfe.windenergie-geschwindigkeit_h125",
    "ch.bfe.windenergie-geschwindigkeit_h150",
    "ch.bfe.windenergie-geschwindigkeit_h50",
    "ch.bfe.windenergie-geschwindigkeit_h75",
    "ch.bfe.windenergie-potenzialgebiete",
    "ch.bfe.windenergieanlagen",
    "ch.bfs.arealstatistik",
    "ch.bfs.arealstatistik-bodenbedeckung",
    "ch.bfs.arealstatistik-waldmischungsgrad",
    "ch.bfs.betriebszaehlungen-arbeitsstaetten",
    "ch.bfs.betriebszaehlungen-beschaeftigte_vollzeitaequivalente",
    "ch.bfs.erreichbarkeit-apotheken",
    "ch.bfs.erreichbarkeit-restaurants",
    "ch.bfs.gebaeude_wohnungs_register",
    "ch.bfs.gebaeude_wohnungs_register_waermequelle_heizung",
    "ch.bfs.generalisierte-grenzen_agglomerationen_g1",
    "ch.bfs.generalisierte-grenzen_agglomerationen_g2",
    "ch.bfs.landschaftswandel",
    "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner",
    "ch.bfs.volkszaehlung-gebaeudestatistik_gebaeude",
    "ch.bfs.volkszaehlung-gebaeudestatistik_wohnungen",
    "ch.blw.alpprodukte",
    "ch.blw.bergprodukte",
    "ch.blw.bewaesserungsbeduerftigkeit",
    "ch.blw.bodeneignung-gruendigkeit",
    "ch.blw.bodeneignung-kulturland",
    "ch.blw.bodeneignung-kulturtyp",
    "ch.blw.bodeneignung-naehrstoffspeichervermoegen",
    "ch.blw.bodeneignung-skelettgehalt",
    "ch.blw.bodeneignung-vernaessung",
    "ch.blw.bodeneignung-wasserdurchlaessigkeit",
    "ch.blw.bodeneignung-wasserspeichervermoegen",
    "ch.blw.erosion",
    "ch.blw.erosion-fliesswegkarte",
    "ch.blw.erosion-quantitativ",
    "ch.blw.feldblockkarte",
    "ch.blw.gewaesseranschlusskarte",
    "ch.blw.gewaesseranschlusskarte-direkt",
    "ch.blw.hang_steillagen",
    "ch.blw.hanglagen-abschwemmung",
    "ch.blw.klimaeignung-futterbau",
    "ch.blw.klimaeignung-getreidebau",
    "ch.blw.klimaeignung-kartoffeln",
    "ch.blw.klimaeignung-koernermais",
    "ch.blw.klimaeignung-kulturland",
    "ch.blw.klimaeignung-spezialkulturen",
    "ch.blw.klimaeignung-typ",
    "ch.blw.klimaeignung-zwischenfruchtbau",
    "ch.blw.landwirtschaftliche-zonengrenzen",
    "ch.blw.milchmarktregionen",
    "ch.blw.niederschlagshaushalt",
    "ch.blw.steil_terrassenlagen_rebbau",
    "ch.blw.ursprungsbezeichnungen-fleisch",
    "ch.blw.ursprungsbezeichnungen-kaese",
    "ch.blw.ursprungsbezeichnungen-konditoreiwaren",
    "ch.blw.ursprungsbezeichnungen-pflanzen",
    "ch.blw.ursprungsbezeichnungen-spirituosen",
    "ch.ensi.zonenplan-notfallschutz-kernanlagen",
    "ch.kantone.cadastralwebmap-farbe",
    "ch.meteoschweiz.hagelgefaehrdung-korngroesse_100_jahre",
    "ch.meteoschweiz.hagelgefaehrdung-korngroesse_10_jahre",
    "ch.meteoschweiz.hagelgefaehrdung-korngroesse_20_jahre",
    "ch.meteoschweiz.hagelgefaehrdung-korngroesse_50_jahre",
    "ch.meteoschweiz.klimanormwerte-niederschlag_1961_1990",
    "ch.meteoschweiz.klimanormwerte-niederschlag_aktuelle_periode",
    "ch.meteoschweiz.klimanormwerte-sonnenscheindauer_1961_1990",
    "ch.meteoschweiz.klimanormwerte-sonnenscheindauer_aktuelle_periode",
    "ch.meteoschweiz.klimanormwerte-temperatur_1961_1990",
    "ch.meteoschweiz.klimanormwerte-temperatur_aktuelle_periode",
    "ch.meteoschweiz.klimaszenarien-raumklima",
    "ch.meteoschweiz.messnetz-atmosphaere",
    "ch.meteoschweiz.messnetz-automatisch",
    "ch.meteoschweiz.messnetz-beobachtungen",
    "ch.meteoschweiz.messnetz-flugwetter",
    "ch.meteoschweiz.messnetz-klima",
    "ch.meteoschweiz.messnetz-manuell",
    "ch.meteoschweiz.messnetz-partner",
    "ch.meteoschweiz.messnetz-phaenologie",
    "ch.meteoschweiz.messnetz-pollen",
    "ch.meteoschweiz.messnetz-webcams",
    "ch.meteoschweiz.messwerte-foehn-10min",
    "ch.meteoschweiz.messwerte-gesamtschnee-1d",
    "ch.meteoschweiz.messwerte-globalstrahlung-10min",
    "ch.meteoschweiz.messwerte-globalstrahlung-1d",
    "ch.meteoschweiz.messwerte-luftdruck-700hpa-flaeche-10min",
    "ch.meteoschweiz.messwerte-luftdruck-850hpa-flaeche-10min",
    "ch.meteoschweiz.messwerte-luftdruck-differenz-3h",
    "ch.meteoschweiz.messwerte-luftdruck-qfe-10min",
    "ch.meteoschweiz.messwerte-luftdruck-qff-10min",
    "ch.meteoschweiz.messwerte-luftdruck-qnh-10min",
    "ch.meteoschweiz.messwerte-luftfeuchtigkeit-10min",
    "ch.meteoschweiz.messwerte-lufttemperatur-10min",
    "ch.meteoschweiz.messwerte-lufttemperatur-24h-max-1h",
    "ch.meteoschweiz.messwerte-lufttemperatur-24h-min-1h",
    "ch.meteoschweiz.messwerte-neuschnee-1d",
    "ch.meteoschweiz.messwerte-neuschnee-2d",
    "ch.meteoschweiz.messwerte-neuschnee-3d",
    "ch.meteoschweiz.messwerte-niederschlag-10min",
    "ch.meteoschweiz.messwerte-niederschlag-1d",
    "ch.meteoschweiz.messwerte-niederschlag-1h",
    "ch.meteoschweiz.messwerte-niederschlag-24h",
    "ch.meteoschweiz.messwerte-niederschlag-48h",
    "ch.meteoschweiz.messwerte-niederschlag-72h",
    "ch.meteoschweiz.messwerte-pollen-birke-1h",
    "ch.meteoschweiz.messwerte-pollen-buche-1h",
    "ch.meteoschweiz.messwerte-pollen-eiche-1h",
    "ch.meteoschweiz.messwerte-pollen-erle-1h",
    "ch.meteoschweiz.messwerte-pollen-esche-1h",
    "ch.meteoschweiz.messwerte-pollen-graeser-1h",
    "ch.meteoschweiz.messwerte-pollen-hasel-1h",
    "ch.meteoschweiz.messwerte-sonnenscheindauer-10min",
    "ch.meteoschweiz.messwerte-sonnenscheindauer-kumuliert-10min",
    "ch.meteoschweiz.messwerte-sonnenscheindauer-relativ-1d",
    "ch.meteoschweiz.messwerte-taupunkt-10min",
    "ch.meteoschweiz.messwerte-wind-boeenspitze-kmh-10min",
    "ch.meteoschweiz.messwerte-wind-boeenspitze-kmh-6h",
    "ch.meteoschweiz.messwerte-windgeschwindigkeit-kmh-10min",
    "ch.nagra.aeromagnetische-karte_1100",
    "ch.nagra.aeromagnetische-karte_1500",
    "ch.pronatura.naturschutzgebiete",
    "ch.sem.sachplan-asyl_kraft",
    "ch.swisstopo-vd.amtliche-vermessung",
    "ch.swisstopo-vd.geometa-gemeinde",
    "ch.swisstopo-vd.geometa-grundbuch",
    "ch.swisstopo-vd.geometa-nfgeom",
    "ch.swisstopo-vd.geometa-periodische_nachfuehrung",
    "ch.swisstopo-vd.geometa-standav",
    "ch.swisstopo-vd.ortschaftenverzeichnis_plz",
    "ch.swisstopo-vd.spannungsarme-gebiete",
    "ch.swisstopo-vd.stand-oerebkataster",
    "ch.swisstopo.amtliches-gebaeudeadressverzeichnis",
    "ch.swisstopo.amtliches-strassenverzeichnis",
    "ch.swisstopo.dreiecksvermaschung",
    "ch.swisstopo.fixpunkte-agnes",
    "ch.swisstopo.fixpunkte-hfp1",
    "ch.swisstopo.fixpunkte-hfp2",
    "ch.swisstopo.fixpunkte-lfp1",
    "ch.swisstopo.fixpunkte-lfp2",
    "ch.swisstopo.geoidmodell-ch1903",
    "ch.swisstopo.geoidmodell-etrs89",
    "ch.swisstopo.geologie-bodenunruhe",
    "ch.swisstopo.geologie-bohrungen_tiefer_500",
    "ch.swisstopo.geologie-dosisleistung-terrestrisch",
    "ch.swisstopo.geologie-eiszeit-lgm",
    "ch.swisstopo.geologie-eiszeit-lgm-raster",
    "ch.swisstopo.geologie-felslabore",
    "ch.swisstopo.geologie-felsoberflaeche_hoehenmodell",
    "ch.swisstopo.geologie-generalkarte-ggk200",
    "ch.swisstopo.geologie-generalkarte-ggk200.metadata",
    "ch.swisstopo.geologie-geocover.metadata",
    "ch.swisstopo.geologie-geodaesie-bouguer_anomalien",
    "ch.swisstopo.geologie-geodaesie-isostatische_anomalien",
    "ch.swisstopo.geologie-geoevents_anfrage",
    "ch.swisstopo.geologie-geoevents_demnaechst",
    "ch.swisstopo.geologie-geologische_3dmodelle",
    "ch.swisstopo.geologie-geologische_karte",
    "ch.swisstopo.geologie-geologischer_atlas.metadata",
    "ch.swisstopo.geologie-geologischer_atlas_profile",
    "ch.swisstopo.geologie-geomol-temperaturmodell_eingangsdaten",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_1000",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_1500",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_2000",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_3000",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_4000",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_500",
    "ch.swisstopo.geologie-geomorphologie",
    "ch.swisstopo.geologie-geophysik-aeromagnetische_karte_jura",
    "ch.swisstopo.geologie-geophysik-aeromagnetische_karte_schweiz",
    "ch.swisstopo.geologie-geophysik-deklination",
    "ch.swisstopo.geologie-geophysik-geothermie",
    "ch.swisstopo.geologie-geophysik-inklination",
    "ch.swisstopo.geologie-geophysik-totalintensitaet",
    "ch.swisstopo.geologie-geosites",
    "ch.swisstopo.geologie-geotechnik-gk200",
    "ch.swisstopo.geologie-geotechnik-gk500-genese",
    "ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung",
    "ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen",
    "ch.swisstopo.geologie-geotechnik-mineralische_rohstoffe200",
    "ch.swisstopo.geologie-geotechnik-steinbrueche_1915",
    "ch.swisstopo.geologie-geotechnik-steinbrueche_1965",
    "ch.swisstopo.geologie-geotechnik-steinbrueche_1980",
    "ch.swisstopo.geologie-geotechnik-steinbrueche_1995",
    "ch.swisstopo.geologie-geotechnik-steine_historische_bauwerke",
    "ch.swisstopo.geologie-geothermische_potenzialstudien_regional",
    "ch.swisstopo.geologie-geotope",
    "ch.swisstopo.geologie-geotope_kantone_stand",
    "ch.swisstopo.geologie-geowege",
    "ch.swisstopo.geologie-gesteinsdichte",
    "ch.swisstopo.geologie-gletscherausdehnung",
    "ch.swisstopo.geologie-gletschermaechtigkeit",
    "ch.swisstopo.geologie-gravimetrischer_atlas",
    "ch.swisstopo.geologie-gravimetrischer_atlas.messpunkte",
    "ch.swisstopo.geologie-hydrogeologische_karte-grundwasservorkommen",
    "ch.swisstopo.geologie-hydrogeologische_karte-grundwasservulnerabilitaet",
    "ch.swisstopo.geologie-lockergestein_maechtigkeitsmodell",
    "ch.swisstopo.geologie-reflexionsseismik",
    "ch.swisstopo.geologie-rohstoffe-gebrochene_gesteine_abbau",
    "ch.swisstopo.geologie-rohstoffe-gips_abbau_verarbeitung",
    "ch.swisstopo.geologie-rohstoffe-industrieminerale",
    "ch.swisstopo.geologie-rohstoffe-kohlen_bitumen_erdgas",
    "ch.swisstopo.geologie-rohstoffe-naturwerksteine_abbau",
    "ch.swisstopo.geologie-rohstoffe-salz_abbau_verarbeitung",
    "ch.swisstopo.geologie-rohstoffe-vererzungen",
    "ch.swisstopo.geologie-rohstoffe-zement_abbau_verarbeitung",
    "ch.swisstopo.geologie-rohstoffe-ziegel_abbau",
    "ch.swisstopo.geologie-spezialkarten_schweiz.metadata",
    "ch.swisstopo.geologie-spezialkarten_schweiz_vector.metadata",
    "ch.swisstopo.geologie-tektonische_karte",
    "ch.swisstopo.geologie-tiefengeothermie_projekte",
    "ch.swisstopo.hebungsraten",
    "ch.swisstopo.hiks-dufour.metadata",
    "ch.swisstopo.hiks-siegfried-ta25.metadata",
    "ch.swisstopo.hiks-siegfried-ta50.metadata",
    "ch.swisstopo.images-swissimage-dop10.metadata",
    "ch.swisstopo.koordinatenaenderung",
    "ch.swisstopo.landesschwerenetz",
    "ch.swisstopo.leichte-basiskarte_reliefschattierung",
    "ch.swisstopo.lotabweichungen",
    "ch.swisstopo.lubis-bildstreifen",
    "ch.swisstopo.lubis-luftbilder-dritte-firmen",
    "ch.swisstopo.lubis-luftbilder-dritte-kantone",
    "ch.swisstopo.lubis-luftbilder_farbe",
    "ch.swisstopo.lubis-luftbilder_infrarot",
    "ch.swisstopo.lubis-luftbilder_schraegaufnahmen",
    "ch.swisstopo.lubis-luftbilder_schwarzweiss",
    "ch.swisstopo.lubis-terrestrische_aufnahmen",
    "ch.swisstopo.meldungen-karten_geodaten",
    "ch.swisstopo.pixelkarte-farbe-pk1000.noscale",
    "ch.swisstopo.pixelkarte-pk100.metadata",
    "ch.swisstopo.pixelkarte-pk200.metadata",
    "ch.swisstopo.pixelkarte-pk25.metadata",
    "ch.swisstopo.pixelkarte-pk50.metadata",
    "ch.swisstopo.schneeschuhwandern",
    "ch.swisstopo.strassenkarte-200",
    "ch.swisstopo.swissboundaries3d-bezirk-flaeche.fill",
    "ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill",
    "ch.swisstopo.swissboundaries3d-kanton-flaeche.fill",
    "ch.swisstopo.swissboundaries3d-land-flaeche.fill",
    "ch.swisstopo.swissimage-product.metadata",
    "ch.swisstopo.swissnames3d",
    "ch.swisstopo.swisssurface3d-raster.metadata",
    "ch.swisstopo.swisssurface3d.metadata",
    "ch.swisstopo.swisstne-base",
    "ch.swisstopo.transformation-bezugsrahmen_hoehe",
    "ch.swisstopo.transformationsgenauigkeit",
    "ch.swisstopo.treasurehunt",
    "ch.swisstopo.vec200-adminboundaries-protectedarea",
    "ch.swisstopo.verschiebungsvektoren-tsp1",
    "ch.swisstopo.verschiebungsvektoren-tsp2",
    "ch.vbs.armee-kriegsdenkmaeler",
    "ch.vbs.armeelogistikcenter",
    "ch.vbs.bundestankstellen-bebeco",
    "ch.vbs.grunddispositiv-zeus",
    "ch.vbs.kataster-belasteter-standorte-militaer",
    "ch.vbs.logistikraeume-armeelogistikcenter",
    "ch.vbs.milairspacechart",
    "ch.vbs.panzerverschiebungsrouten",
    "ch.vbs.patrouilledesglaciers-a_rennen",
    "ch.vbs.patrouilledesglaciers-z_rennen",
    "ch.vbs.retablierungsstellen",
    "ch.vbs.sachplan-infrastruktur-militaer_anhoerung",
    "ch.vbs.sachplan-infrastruktur-militaer_kraft",
    "ch.vbs.schiessanzeigen",
    "ch.vbs.sperr-gefahrenzonenkarte",
    "ch.vbs.swissmilpilotschart",
    "ch.vbs.territorialregionen",
    "ch.vbs.waldschadenkarte",
    "org.epsg.grid_2056",
    "org.epsg.grid_21781",
    "org.epsg.grid_4326"
    ]

some_of_all_ch_layers = [
    'ch.are.bauzonen',
    'ch.are.erreichbarkeit-miv',
    'ch.are.erreichbarkeit-oev',
    'ch.are.gemeindetypen',
    'ch.are.gueteklassen_oev',
    'ch.are.landschaftstypen',
    'ch.are.reisezeit-agglomerationen-miv',
    'ch.are.reisezeit-agglomerationen-oev',
    'ch.are.reisezeit-miv',
    'ch.are.reisezeit-oev',
    'ch.are.windenergie-bundesinteressen',
    'ch.are.wohnungsinventar-zweitwohnungsanteil',
    'ch.astra.schwerverunfallte-kanton_alkohol',
    'ch.astra.schwerverunfallte-kanton_geschwindigkeit',
    'ch.astra.schwerverunfallte-kanton_jahresvergleich',
    'ch.astra.schwerverunfallte-kanton_pro_einwohner',
    'ch.bafu.biogeographische_regionen',
    'ch.bafu.flora-weltensutter_atlas',
    'ch.bafu.gefahren-waldbrand_praeventionsmassnahmen_kantone',
    'ch.bafu.gefahren-waldbrand_warnung',
    'ch.bafu.grundwasserkoerper',
    'ch.bafu.hydrogeologische-karte_100',
    'ch.bafu.hydrologie-hintergrundkarte',
    'ch.bafu.hydrologischer-atlas_basisgebiete',
    'ch.bafu.hydrologischer-atlas_bilanzgebiete',
    'ch.bafu.hydrologischer-atlas_flussgebiete',
    'ch.bafu.landesforstinventar-kantone',
    'ch.bafu.landesforstinventar-produktionsregionen',
    'ch.bafu.landesforstinventar-schutzwaldregionen',
    'ch.bafu.landesforstinventar-vegetationshoehenmodell',
    'ch.bafu.landesforstinventar-vegetationshoehenmodell_relief',
    'ch.bafu.landesforstinventar-wirtschaftsregionen',
    'ch.bafu.lebensraumkarte-schweiz',
    'ch.bafu.sturm-boeenspitzen_100',
    'ch.bafu.sturm-boeenspitzen_30',
    'ch.bafu.sturm-boeenspitzen_300',
    'ch.bafu.sturm-boeenspitzen_50',
    'ch.bafu.sturm-staudruck_100',
    'ch.bafu.sturm-staudruck_30',
    'ch.bafu.sturm-staudruck_300',
    'ch.bafu.sturm-staudruck_50',
    'ch.bafu.wasser-teileinzugsgebiete_2',
    'ch.bafu.wasser-teileinzugsgebiete_40',
    'ch.bag.radonkarte',
    'ch.bag.zecken-fsme-impfung',
    'ch.bakom.anbieter-eigenes_festnetz',
    'ch.bakom.notruf',
    # 'ch.bakom.notruf-112_festnetz',
    # 'ch.bakom.notruf-112_mobilnetz',
    # 'ch.bakom.notruf-112_satellit',
    # 'ch.bakom.notruf-112_zentral',
    # 'ch.bakom.notruf-117_festnetz',
    # 'ch.bakom.notruf-117_mobilnetz',
    # 'ch.bakom.notruf-117_zentral',
    # 'ch.bakom.notruf-118_festnetz',
    # 'ch.bakom.notruf-118_mobilnetz',
    # 'ch.bakom.notruf-118_zentral',
    # 'ch.bakom.notruf-143_festnetz',
    # 'ch.bakom.notruf-143_mobilnetz',
    # 'ch.bakom.notruf-143_zentral',
    # 'ch.bakom.notruf-144_festnetz',
    # 'ch.bakom.notruf-144_mobilnetz',
    # 'ch.bakom.notruf-144_zentral',
    # 'ch.bakom.notruf-145_festnetz',
    # 'ch.bakom.notruf-145_mobilnetz',
    # 'ch.bakom.notruf-145_zentral',
    # 'ch.bakom.notruf-147_festnetz',
    # 'ch.bakom.notruf-147_mobilnetz',
    # 'ch.bakom.notruf-147_zentral',
    'ch.bakom.versorgungsgebiet-tv',
    'ch.bakom.versorgungsgebiet-ukw',
    # 'ch.bazl.bebaute-gebiete_luftfahrtrecht',
    'ch.bazl.intrinsisches-bodenrisiko_sora',
    # 'ch.bazl.luftraeume-fluginformationsgebiet',
    # 'ch.bazl.luftraeume-kontrollbezirke',
    'ch.bfe.biomasse-nicht-verholzt',
    'ch.bfe.biomasse-verholzt',
    'ch.bfe.energieberatungsstellen',
    'ch.bfe.fernwaerme-nachfrage_wohn_dienstleistungsgebaeude',
    'ch.bfe.meteorologische-vereisung',
    'ch.bfe.solarenergie-eignung-daecher',
    'ch.bfe.solarenergie-eignung-fassaden',
    'ch.bfe.windenergie-geschwindigkeit_h100',
    'ch.bfe.windenergie-geschwindigkeit_h125',
    'ch.bfe.windenergie-geschwindigkeit_h150',
    'ch.bfe.windenergie-geschwindigkeit_h50',
    'ch.bfe.windenergie-geschwindigkeit_h75',
    'ch.bfs.betriebszaehlungen-arbeitsstaetten',
    'ch.bfs.betriebszaehlungen-beschaeftigte_vollzeitaequivalente',
    'ch.bfs.generalisierte-grenzen_agglomerationen_g1',
    'ch.bfs.generalisierte-grenzen_agglomerationen_g2',
    'ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner',
    'ch.bfs.volkszaehlung-gebaeudestatistik_gebaeude',
    'ch.bfs.volkszaehlung-gebaeudestatistik_wohnungen',
    'ch.blw.bodeneignung-gruendigkeit',
    'ch.blw.bodeneignung-kulturland',
    'ch.blw.bodeneignung-kulturtyp',
    'ch.blw.bodeneignung-naehrstoffspeichervermoegen',
    'ch.blw.bodeneignung-skelettgehalt',
    'ch.blw.bodeneignung-vernaessung',
    'ch.blw.bodeneignung-wasserdurchlaessigkeit',
    'ch.blw.bodeneignung-wasserspeichervermoegen',
    'ch.blw.klimaeignung-futterbau',
    'ch.blw.klimaeignung-getreidebau',
    'ch.blw.klimaeignung-kartoffeln',
    'ch.blw.klimaeignung-koernermais',
    'ch.blw.klimaeignung-kulturland',
    'ch.blw.klimaeignung-spezialkulturen',
    'ch.blw.klimaeignung-typ',
    'ch.blw.klimaeignung-zwischenfruchtbau',
    # 'ch.blw.milchmarktregionen',
    'ch.blw.niederschlagshaushalt',
    'ch.blw.ursprungsbezeichnungen-fleisch',
    'ch.blw.ursprungsbezeichnungen-kaese',
    'ch.kantone.cadastralwebmap-farbe',
    'ch.swisstopo-vd.amtliche-vermessung',
    'ch.swisstopo-vd.geometa-gemeinde',
    'ch.swisstopo-vd.geometa-grundbuch',
    'ch.swisstopo-vd.geometa-nfgeom',
    'ch.swisstopo-vd.geometa-periodische_nachfuehrung',
    'ch.swisstopo-vd.ortschaftenverzeichnis_plz',
    'ch.swisstopo-vd.spannungsarme-gebiete',
    'ch.swisstopo-vd.stand-oerebkataster',
    'ch.swisstopo.dreiecksvermaschung',
    'ch.swisstopo.geologie-eiszeit-lgm',
    'ch.swisstopo.geologie-felsoberflaeche_hoehenmodell',
    'ch.swisstopo.geologie-generalkarte-ggk200.metadata',
    'ch.swisstopo.geologie-geocover.metadata',
    'ch.swisstopo.geologie-geologische_3dmodelle',
    'ch.swisstopo.geologie-geologische_karte',
    'ch.swisstopo.geologie-geologischer_atlas.metadata',
    'ch.swisstopo.geologie-geomol-temperaturverteilung_1000',
    'ch.swisstopo.geologie-geomol-temperaturverteilung_1500',
    'ch.swisstopo.geologie-geomol-temperaturverteilung_2000',
    'ch.swisstopo.geologie-geomol-temperaturverteilung_3000',
    'ch.swisstopo.geologie-geomol-temperaturverteilung_4000',
    'ch.swisstopo.geologie-geomol-temperaturverteilung_500',
    'ch.swisstopo.geologie-geomorphologie',
    'ch.swisstopo.geologie-geotechnik-gk200',
    'ch.swisstopo.geologie-geotechnik-gk500-genese',
    'ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung',
    'ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen',
    'ch.swisstopo.geologie-geothermische_potenzialstudien_regional',
    'ch.swisstopo.geologie-geotope_kantone_stand',
    'ch.swisstopo.geologie-gesteinsdichte',
    'ch.swisstopo.geologie-hydrogeologische_karte-grundwasservorkommen',
    'ch.swisstopo.geologie-hydrogeologische_karte-grundwasservulnerabilitaet',
    'ch.swisstopo.geologie-lockergestein_maechtigkeitsmodell',
    'ch.swisstopo.geologie-spezialkarten_schweiz.metadata',
    'ch.swisstopo.geologie-tektonische_karte',
    'ch.swisstopo.hiks-dufour.metadata',
    'ch.swisstopo.hiks-siegfried-ta25.metadata',
    'ch.swisstopo.images-swissimage-dop10.metadata',
    'ch.swisstopo.pixelkarte-pk100.metadata',
    'ch.swisstopo.pixelkarte-pk200.metadata',
    'ch.swisstopo.pixelkarte-pk25.metadata',
    'ch.swisstopo.pixelkarte-pk50.metadata',
    'ch.swisstopo.swissboundaries3d-bezirk-flaeche.fill',
    'ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill',
    'ch.swisstopo.swissboundaries3d-kanton-flaeche.fill',
    'ch.swisstopo.swissboundaries3d-land-flaeche.fill',
    'ch.swisstopo.swissimage-product.metadata',
    'ch.swisstopo.swissnames3d',
    'ch.swisstopo.transformationsgenauigkeit',
    'ch.vbs.logistikraeume-armeelogistikcenter',
    'ch.vbs.territorialregionen'
    ]

html_popup_layers = [
    "ch.are.agglomerationsverkehr",
    "ch.are.alpenkonvention",
    "ch.are.bauzonen",
    "ch.are.belastung-personenverkehr-bahn",
    "ch.are.belastung-personenverkehr-bahn_zukunft",
    "ch.are.belastung-personenverkehr-strasse",
    "ch.are.belastung-personenverkehr-strasse_zukunft",
    "ch.are.erreichbarkeit-miv",
    "ch.are.erreichbarkeit-oev",
    "ch.are.gemeindetypen",
    "ch.are.gueteklassen_oev",
    "ch.are.landschaftstypen",
    "ch.are.reisezeit-agglomerationen-miv",
    "ch.are.reisezeit-agglomerationen-oev",
    "ch.are.reisezeit-miv",
    "ch.are.reisezeit-oev",
    "ch.are.windenergie-bundesinteressen",
    "ch.are.wohnungsinventar-zweitwohnungsanteil",
    "ch.astra.baulinien-nationalstrassen",
    "ch.astra.hauptstrassennetz",
    "ch.astra.ivs-nat",
    "ch.astra.ivs-nat-verlaeufe",
    "ch.astra.ivs-reg_loc",
    "ch.astra.mountainbikeland",
    "ch.astra.mountainbikeland-sperrungen_umleitungen",
    "ch.astra.nationalstrassenachsen",
    "ch.astra.sachplan-infrastruktur-strasse_kraft",
    # "ch.astra.schwerverunfallte-kanton_alkohol",
    # "ch.astra.schwerverunfallte-kanton_geschwindigkeit",
    # "ch.astra.schwerverunfallte-kanton_jahresvergleich",
    # "ch.astra.schwerverunfallte-kanton_pro_einwohner",
    "ch.astra.skatingland",
    "ch.astra.skatingland-sperrungen_umleitungen",
    "ch.astra.strassenverkehrszaehlung-uebergeordnet",
    # "ch.astra.unfaelle-personenschaeden_alle",
    # "ch.astra.unfaelle-personenschaeden_fahrraeder",
    # "ch.astra.unfaelle-personenschaeden_fussgaenger",
    # "ch.astra.unfaelle-personenschaeden_getoetete",
    # "ch.astra.unfaelle-personenschaeden_motorraeder",
    "ch.astra.veloland",
    "ch.astra.veloland-sperrungen_umleitungen",
    "ch.astra.wanderland",
    "ch.astra.wanderland-sperrungen_umleitungen",
    "ch.babs.kulturgueter",
    # "ch.bafu.alpweiden-herdenschutzhunde",
    "ch.bafu.amphibienwanderung-verkehrskonflikte",
    "ch.bafu.auen-ausserhalb_bundesinventar",
    "ch.bafu.auen-ausserhalb_bundesinventar_alpin",
    "ch.bafu.auen-vegetationskarten",
    "ch.bafu.biogeographische_regionen",
    "ch.bafu.bundesinventare-amphibien",
    "ch.bafu.bundesinventare-amphibien_anhang4",
    "ch.bafu.bundesinventare-amphibien_wanderobjekte",
    "ch.bafu.bundesinventare-auen",
    "ch.bafu.bundesinventare-auen_anhang2",
    "ch.bafu.bundesinventare-auen_vegetation_alpin",
    "ch.bafu.bundesinventare-bln",
    "ch.bafu.bundesinventare-flachmoore",
    "ch.bafu.bundesinventare-hochmoore",
    # "ch.bafu.bundesinventare-jagdbanngebiete",
    "ch.bafu.bundesinventare-moorlandschaften",
    "ch.bafu.bundesinventare-trockenwiesen_trockenweiden",
    "ch.bafu.bundesinventare-trockenwiesen_trockenweiden_anhang2",
    "ch.bafu.bundesinventare-vogelreservate",
    # "ch.bafu.fauna-steinbockkolonien",
    "ch.bafu.fauna-wildtierkorridor_national",
    "ch.bafu.fauna-wildtierpassagen",
    "ch.bafu.feststoffe-geschiebemessnetz",
    # "ch.bafu.fischerei-krebspest",
    "ch.bafu.flora-weltensutter_atlas",
    "ch.bafu.flussordnungszahlen-strahler",
    "ch.bafu.gefahren-baugrundklassen",
    "ch.bafu.gefahren-historische_erdbeben",
    "ch.bafu.gefahren-spektral",
    "ch.bafu.gefahren-waldbrand_praeventionsmassnahmen_kantone",
    "ch.bafu.gefahren-waldbrand_warnung",
    "ch.bafu.gewaesser-uferbestockung",
    "ch.bafu.gewaesserschutz-badewasserqualitaet",
    # "ch.bafu.gewaesserschutz-biologischer_zustand_diatomeen",
    # "ch.bafu.gewaesserschutz-biologischer_zustand_fische",
    # "ch.bafu.gewaesserschutz-biologischer_zustand_makrophyten",
    # "ch.bafu.gewaesserschutz-biologischer_zustand_makrozoobenthos",
    # "ch.bafu.gewaesserschutz-chemischer_zustand_ammonium",
    # "ch.bafu.gewaesserschutz-chemischer_zustand_doc",
    # "ch.bafu.gewaesserschutz-chemischer_zustand_nitrat",
    # "ch.bafu.gewaesserschutz-chemischer_zustand_nitrit",
    # "ch.bafu.gewaesserschutz-chemischer_zustand_phosphat",
    # "ch.bafu.gewaesserschutz-chemischer_zustand_phosphor_gesamt",
    # "ch.bafu.gewaesserschutz-klaeranlagen_anteilq347",
    # "ch.bafu.gewaesserschutz-klaeranlagen_ausbaugroesse",
    # "ch.bafu.gewaesserschutz-klaeranlagen_reinigungstyp",
    "ch.bafu.grundwasserkoerper",
    "ch.bafu.hydrogeologie-markierversuche",
    "ch.bafu.hydrogeologische-karte_100",
    "ch.bafu.hydrologie-daueruntersuchung_fliessgewaesser",
    "ch.bafu.hydrologie-gewaesserzustandsmessstationen",
    "ch.bafu.hydrologie-hochwassergrenzwertpegel",
    "ch.bafu.hydrologie-hochwasserstatistik",
    "ch.bafu.hydrologie-hydromessstationen",
    "ch.bafu.hydrologie-niedrigwasserstatistik",
    "ch.bafu.hydrologie-q347",
    "ch.bafu.hydrologie-untersuchungsgebiete",
    "ch.bafu.hydrologie-untersuchungsgebiete_stationen",
    "ch.bafu.hydrologie-wassertemperaturmessstationen",
    "ch.bafu.hydrologischer-atlas_basisgebiete",
    "ch.bafu.hydrologischer-atlas_bilanzgebiete",
    "ch.bafu.hydrologischer-atlas_flussgebiete",
    "ch.bafu.hydrologischer-atlas_kantonale-messstationen",
    "ch.bafu.karst-ausdehnung_grundwasservorkommen",
    "ch.bafu.karst-einzugsgebiete",
    "ch.bafu.karst-einzugsgebietseinheiten",
    "ch.bafu.karst-quellen_schwinden",
    "ch.bafu.karst-unterirdische_fliesswege",
    "ch.bafu.klima-co2_ausstoss_gebaeude",
    # "ch.bafu.landesforstinventar-kantone",
    # "ch.bafu.landesforstinventar-produktionsregionen",
    "ch.bafu.landesforstinventar-schutzwaldregionen",
    "ch.bafu.landesforstinventar-vegetationshoehenmodell",
    "ch.bafu.landesforstinventar-vegetationshoehenmodell_relief",
    "ch.bafu.landesforstinventar-wirtschaftsregionen",
    "ch.bafu.lebensraumkarte-schweiz",
    "ch.bafu.mittlere-abfluesse",
    "ch.bafu.mittlere-abfluesse_zukunft",
    "ch.bafu.moose",
    "ch.bafu.nabelstationen",
    "ch.bafu.oekomorphologie-f_abschnitte",
    "ch.bafu.oekomorphologie-f_abstuerze",
    "ch.bafu.oekomorphologie-f_bauwerke",
    "ch.bafu.schutzgebiete-aulav_auen",
    # "ch.bafu.schutzgebiete-aulav_jagdbanngebiete",
    "ch.bafu.schutzgebiete-aulav_moorlandschaften",
    "ch.bafu.schutzgebiete-aulav_uebrige",
    "ch.bafu.schutzgebiete-biosphaerenreservate",
    "ch.bafu.schutzgebiete-paerke_nationaler_bedeutung",
    "ch.bafu.schutzgebiete-paerke_nationaler_bedeutung_perimeter",
    "ch.bafu.schutzgebiete-ramsar",
    "ch.bafu.schutzgebiete-smaragd",
    # "ch.bafu.strukturguete-hochrhein_linkesufer",
    # "ch.bafu.strukturguete-hochrhein_linkesumfeld",
    # "ch.bafu.strukturguete-hochrhein_rechtesufer",
    # "ch.bafu.strukturguete-hochrhein_rechtesumfeld",
    # "ch.bafu.strukturguete-hochrhein_sohle",
    # "ch.bafu.sturm-boeenspitzen_100",
    "ch.bafu.sturm-boeenspitzen_30",
    # "ch.bafu.sturm-boeenspitzen_300",
    # "ch.bafu.sturm-boeenspitzen_50",
    "ch.bafu.sturm-staudruck_100",
    "ch.bafu.sturm-staudruck_30",
    "ch.bafu.sturm-staudruck_300",
    "ch.bafu.sturm-staudruck_50",
    "ch.bafu.swissprtr",
    "ch.bafu.tranquillity-gebiete",
    "ch.bafu.typisierung-fliessgewaesser",
    "ch.bafu.vec25-gewaessernetz_2000",
    "ch.bafu.vec25-seen",
    "ch.bafu.waldreservate",
    "ch.bafu.wasser-entnahme",
    "ch.bafu.wasser-gebietsauslaesse",
    "ch.bafu.wasser-leitungen",
    "ch.bafu.wasser-rueckgabe",
    "ch.bafu.wasser-teileinzugsgebiete_2",
    "ch.bafu.wasser-teileinzugsgebiete_40",
    "ch.bafu.wasser-vorfluter",
    "ch.bafu.wasserbau-querprofilmarken",
    "ch.bafu.wasserbau-vermessungsstrecken",
    # "ch.bafu.wrz-jagdbanngebiete_select",
    # "ch.bafu.wrz-wildruhezonen_portal",
    "ch.bag.radioaktivitaet-atmosphaere",
    "ch.bag.radonkarte",
    "ch.bag.zecken-fsme-faelle",
    "ch.bag.zecken-fsme-impfung",
    "ch.bak.bundesinventar-schuetzenswerte-ortsbilder",
    "ch.bak.bundesinventar-schuetzenswerte-ortsbilder_fotos",
    "ch.bak.halteplaetze-jenische_sinti_roma",
    "ch.bak.schutzgebiete-unesco_weltkulturerbe",
    "ch.bakom.anbieter-eigenes_festnetz",
    "ch.bakom.notruf",
    # "ch.bakom.notruf-112_festnetz",
    # "ch.bakom.notruf-112_mobilnetz",
    # "ch.bakom.notruf-112_satellit",
    # "ch.bakom.notruf-112_zentral",
    # "ch.bakom.notruf-117_festnetz",
    # "ch.bakom.notruf-117_mobilnetz",
    # "ch.bakom.notruf-117_zentral",
    # "ch.bakom.notruf-118_festnetz",
    # "ch.bakom.notruf-118_mobilnetz",
    # "ch.bakom.notruf-118_zentral",
    # "ch.bakom.notruf-143_festnetz",
    # "ch.bakom.notruf-143_mobilnetz",
    # "ch.bakom.notruf-143_zentral",
    # "ch.bakom.notruf-144_festnetz",
    # "ch.bakom.notruf-144_mobilnetz",
    # "ch.bakom.notruf-144_zentral",
    # "ch.bakom.notruf-145_festnetz",
    # "ch.bakom.notruf-145_mobilnetz",
    # "ch.bakom.notruf-145_zentral",
    # "ch.bakom.notruf-147_festnetz",
    # "ch.bakom.notruf-147_mobilnetz",
    # "ch.bakom.notruf-147_zentral",
    "ch.bakom.radio-fernsehsender",
    "ch.bakom.versorgungsgebiet-tv",
    "ch.bakom.versorgungsgebiet-ukw",
    "ch.baspo.nationales-sportanlagenkonzept",
    "ch.bav.anlagen-schienengueterverkehr",
    "ch.bav.betriebe-stoerfallverordnung_eisenbahnanlagen",
    "ch.bav.haltestellen-oev",
    "ch.bav.kataster-belasteter-standorte-oev",
    "ch.bav.laermbelastung-eisenbahn_effektive_immissionen_nacht",
    "ch.bav.laermbelastung-eisenbahn_effektive_immissionen_tag",
    "ch.bav.laermbelastung-eisenbahn_festgelegte_emissionen_nacht",
    "ch.bav.laermbelastung-eisenbahn_festgelegte_emissionen_tag",
    "ch.bav.laermbelastung-eisenbahn_laermschutzwaende",
    "ch.bav.laermbelastung-eisenbahn_tatsaechliche_emissionen_nacht",
    "ch.bav.laermbelastung-eisenbahn_tatsaechliche_emissionen_tag",
    "ch.bav.laermbelastung-eisenbahn_zulaessige_immissionen_nacht",
    "ch.bav.laermbelastung-eisenbahn_zulaessige_immissionen_tag",
    "ch.bav.lage-stoerfallverordnung_eisenbahnanlagen",
    "ch.bav.sachplan-infrastruktur-schiene_kraft",
    "ch.bav.sachplan-infrastruktur-schifffahrt_kraft",
    "ch.bav.schienennetz",
    "ch.bav.seilbahnen-bundeskonzession",
    "ch.bazl.einschraenkungen-drohnen",
    "ch.bazl.flugplaetze-heliports",
    "ch.bazl.gebirgslandeplaetze",
    "ch.bazl.intrinsisches-bodenrisiko_sora",
    # "ch.bazl.kataster-belasteter-standorte-zivilflugplaetze",
    # "ch.bazl.laermbelastungskataster-zivilflugplaetze_erste-nachtstunde",
    # "ch.bazl.laermbelastungskataster-zivilflugplaetze_helikopter",
    # "ch.bazl.laermbelastungskataster-zivilflugplaetze_helikopter-maximalpegel",
    # "ch.bazl.laermbelastungskataster-zivilflugplaetze_klein-grossflugzeuge",
    # "ch.bazl.laermbelastungskataster-zivilflugplaetze_kleinluftfahrzeuge",
    # "ch.bazl.laermbelastungskataster-zivilflugplaetze_letzte-nachtstunde",
    # "ch.bazl.laermbelastungskataster-zivilflugplaetze_militaer-gesamt",
    # "ch.bazl.laermbelastungskataster-zivilflugplaetze_zweite-nachtstunde",
    # "ch.bazl.luftfahrthindernis",
    # "ch.bazl.luftfahrthindernis-aenderungen",
    # "ch.bazl.luftfahrthindernis-klein",
    # "ch.bazl.luftraeume-fluginformationsgebiet",
    # "ch.bazl.luftraeume-fluginformationszonen",
    # "ch.bazl.luftraeume-kontrollbezirke",
    # "ch.bazl.luftraeume-kontrollzonen",
    # "ch.bazl.projektierungszonen-flughafenanlagen",
    # "ch.bazl.sachplan-infrastruktur-luftfahrt_kraft",
    "ch.bazl.schutzgebiete-aulav_liechtenstein",
    "ch.bazl.sicherheitszonenplan",
    # "ch.bazl.spitallandeplaetze",
    "ch.bfe.abgeltung-wasserkraftnutzung",
    "ch.bfe.biogasanlagen",
    "ch.bfe.biomasse-nicht-verholzt",
    "ch.bfe.biomasse-verholzt",
    "ch.bfe.elektrische-anlagen_ueber_36",
    "ch.bfe.elektrizitaetsproduktionsanlagen",
    "ch.bfe.energieberatungsstellen",
    "ch.bfe.energieforschung",
    "ch.bfe.energiestaedte",
    "ch.bfe.energiestaedte-2000watt-areale",
    "ch.bfe.erneuerbarheizen",
    "ch.bfe.erneuerbarheizen-mehrfamilienhaeuser",
    "ch.bfe.fernwaerme-angebot",
    "ch.bfe.fernwaerme-nachfrage_industrie",
    "ch.bfe.fernwaerme-nachfrage_wohn_dienstleistungsgebaeude",
    "ch.bfe.kehrichtverbrennungsanlagen",
    "ch.bfe.kernkraftwerke",
    "ch.bfe.kleinwasserkraftpotentiale",
    "ch.bfe.komo-projekte",
    # "ch.bfe.meteorologische-vereisung",
    "ch.bfe.minergiegebaeude",
    "ch.bfe.sachplan-geologie-tiefenlager",
    "ch.bfe.sachplan-uebertragungsleitungen_anhoerung",
    "ch.bfe.sachplan-uebertragungsleitungen_kraft",
    "ch.bfe.solarenergie-eignung-daecher",
    "ch.bfe.solarenergie-eignung-fassaden",
    "ch.bfe.statistik-wasserkraftanlagen",
    "ch.bfe.stauanlagen-bundesaufsicht",
    "ch.bfe.thermische-netze",
    "ch.bfe.waermepotential-gewaesser",
    # "ch.bfe.windenergie-geschwindigkeit_h100",
    # "ch.bfe.windenergie-geschwindigkeit_h125",
    # "ch.bfe.windenergie-geschwindigkeit_h150",
    # "ch.bfe.windenergie-geschwindigkeit_h50",
    "ch.bfe.windenergie-geschwindigkeit_h75",
    "ch.bfe.windenergieanlagen",
    "ch.bfs.arealstatistik",
    "ch.bfs.arealstatistik-bodenbedeckung",
    "ch.bfs.betriebszaehlungen-arbeitsstaetten",
    "ch.bfs.betriebszaehlungen-beschaeftigte_vollzeitaequivalente",
    "ch.bfs.gebaeude_wohnungs_register",
    "ch.bfs.gebaeude_wohnungs_register_waermequelle_heizung",
    "ch.bfs.generalisierte-grenzen_agglomerationen_g1",
    "ch.bfs.generalisierte-grenzen_agglomerationen_g2",
    "ch.bfs.landschaftswandel",
    "ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner",
    "ch.bfs.volkszaehlung-gebaeudestatistik_gebaeude",
    "ch.bfs.volkszaehlung-gebaeudestatistik_wohnungen",
    "ch.blw.bodeneignung-gruendigkeit",
    "ch.blw.bodeneignung-kulturland",
    "ch.blw.bodeneignung-kulturtyp",
    "ch.blw.bodeneignung-naehrstoffspeichervermoegen",
    "ch.blw.bodeneignung-skelettgehalt",
    "ch.blw.bodeneignung-vernaessung",
    "ch.blw.bodeneignung-wasserdurchlaessigkeit",
    "ch.blw.bodeneignung-wasserspeichervermoegen",
    "ch.blw.klimaeignung-futterbau",
    "ch.blw.klimaeignung-getreidebau",
    "ch.blw.klimaeignung-kartoffeln",
    "ch.blw.klimaeignung-koernermais",
    "ch.blw.klimaeignung-kulturland",
    "ch.blw.klimaeignung-spezialkulturen",
    "ch.blw.klimaeignung-typ",
    "ch.blw.klimaeignung-zwischenfruchtbau",
    # "ch.blw.milchmarktregionen",
    "ch.blw.niederschlagshaushalt",
    "ch.blw.ursprungsbezeichnungen-fleisch",
    "ch.blw.ursprungsbezeichnungen-kaese",
    "ch.blw.ursprungsbezeichnungen-konditoreiwaren",
    "ch.blw.ursprungsbezeichnungen-pflanzen",
    "ch.blw.ursprungsbezeichnungen-spirituosen",
    "ch.ensi.zonenplan-notfallschutz-kernanlagen",
    "ch.kantone.cadastralwebmap-farbe",
    "ch.meteoschweiz.klimaszenarien-raumklima",
    "ch.nagra.aeromagnetische-karte_1100",
    "ch.nagra.aeromagnetische-karte_1500",
    "ch.pronatura.naturschutzgebiete",
    "ch.sem.sachplan-asyl_kraft",
    "ch.swisstopo-vd.amtliche-vermessung",
    "ch.swisstopo-vd.geometa-gemeinde",
    "ch.swisstopo-vd.geometa-grundbuch",
    "ch.swisstopo-vd.geometa-nfgeom",
    "ch.swisstopo-vd.geometa-periodische_nachfuehrung",
    "ch.swisstopo-vd.ortschaftenverzeichnis_plz",
    "ch.swisstopo-vd.spannungsarme-gebiete",
    "ch.swisstopo-vd.stand-oerebkataster",
    "ch.swisstopo.amtliches-gebaeudeadressverzeichnis",
    "ch.swisstopo.amtliches-strassenverzeichnis",
    "ch.swisstopo.dreiecksvermaschung",
    "ch.swisstopo.fixpunkte-agnes",
    "ch.swisstopo.fixpunkte-hfp1",
    "ch.swisstopo.fixpunkte-hfp2",
    "ch.swisstopo.fixpunkte-lfp1",
    "ch.swisstopo.fixpunkte-lfp2",
    "ch.swisstopo.geologie-bohrungen_tiefer_500",
    "ch.swisstopo.geologie-dosisleistung-terrestrisch",
    "ch.swisstopo.geologie-eiszeit-lgm",
    "ch.swisstopo.geologie-felslabore",
    "ch.swisstopo.geologie-generalkarte-ggk200.metadata",
    "ch.swisstopo.geologie-geocover",
    "ch.swisstopo.geologie-geocover.metadata",
    "ch.swisstopo.geologie-geodaesie-bouguer_anomalien",
    "ch.swisstopo.geologie-geodaesie-isostatische_anomalien",
    "ch.swisstopo.geologie-geoevents_anfrage",
    "ch.swisstopo.geologie-geoevents_demnaechst",
    "ch.swisstopo.geologie-geologische_3dmodelle",
    "ch.swisstopo.geologie-geologische_karte",
    "ch.swisstopo.geologie-geologischer_atlas",
    "ch.swisstopo.geologie-geologischer_atlas.metadata",
    "ch.swisstopo.geologie-geologischer_atlas_profile",
    "ch.swisstopo.geologie-geomol-temperaturmodell_eingangsdaten",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_1000",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_1500",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_2000",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_3000",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_4000",
    "ch.swisstopo.geologie-geomol-temperaturverteilung_500",
    "ch.swisstopo.geologie-geomorphologie",
    "ch.swisstopo.geologie-geophysik-aeromagnetische_karte_jura",
    "ch.swisstopo.geologie-geophysik-aeromagnetische_karte_schweiz",
    "ch.swisstopo.geologie-geophysik-deklination",
    "ch.swisstopo.geologie-geophysik-geothermie",
    "ch.swisstopo.geologie-geophysik-inklination",
    "ch.swisstopo.geologie-geophysik-totalintensitaet",
    "ch.swisstopo.geologie-geosites",
    "ch.swisstopo.geologie-geotechnik-gk200",
    "ch.swisstopo.geologie-geotechnik-gk500-genese",
    "ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung",
    "ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen",
    "ch.swisstopo.geologie-geotechnik-mineralische_rohstoffe200",
    # "ch.swisstopo.geologie-geotechnik-steinbrueche_1915",
    # "ch.swisstopo.geologie-geotechnik-steinbrueche_1965",
    # "ch.swisstopo.geologie-geotechnik-steinbrueche_1980",
    "ch.swisstopo.geologie-geotechnik-steinbrueche_1995",
    "ch.swisstopo.geologie-geotechnik-steine_historische_bauwerke",
    "ch.swisstopo.geologie-geothermische_potenzialstudien_regional",
    "ch.swisstopo.geologie-geotope",
    "ch.swisstopo.geologie-geotope_kantone_stand",
    "ch.swisstopo.geologie-geowege",
    "ch.swisstopo.geologie-gesteinsdichte",
    "ch.swisstopo.geologie-gletscherausdehnung",
    "ch.swisstopo.geologie-gletschermaechtigkeit",
    "ch.swisstopo.geologie-gravimetrischer_atlas.messpunkte",
    "ch.swisstopo.geologie-hydrogeologische_karte-grundwasservorkommen",
    "ch.swisstopo.geologie-hydrogeologische_karte-grundwasservulnerabilitaet",
    "ch.swisstopo.geologie-reflexionsseismik",
    "ch.swisstopo.geologie-rohstoffe-gebrochene_gesteine_abbau",
    "ch.swisstopo.geologie-rohstoffe-gips_abbau_verarbeitung",
    "ch.swisstopo.geologie-rohstoffe-industrieminerale",
    "ch.swisstopo.geologie-rohstoffe-kohlen_bitumen_erdgas",
    # "ch.swisstopo.geologie-rohstoffe-naturwerksteine_abbau",
    # "ch.swisstopo.geologie-rohstoffe-salz_abbau_verarbeitung",
    # "ch.swisstopo.geologie-rohstoffe-vererzungen",
    # "ch.swisstopo.geologie-rohstoffe-zement_abbau_verarbeitung",
    # "ch.swisstopo.geologie-rohstoffe-ziegel_abbau",
    "ch.swisstopo.geologie-spezialkarten_schweiz.metadata",
    "ch.swisstopo.geologie-spezialkarten_schweiz_vector.metadata",
    "ch.swisstopo.geologie-tektonische_karte",
    "ch.swisstopo.geologie-tiefengeothermie_projekte",
    "ch.swisstopo.hebungsraten",
    "ch.swisstopo.hiks-dufour",
    "ch.swisstopo.hiks-dufour.metadata",
    "ch.swisstopo.hiks-siegfried",
    # "ch.swisstopo.hiks-siegfried-ta25.metadata",
    # "ch.swisstopo.hiks-siegfried-ta50.metadata",
    "ch.swisstopo.images-swissimage-dop10.metadata",
    "ch.swisstopo.landesschwerenetz",
    "ch.swisstopo.lotabweichungen",
    "ch.swisstopo.lubis-bildstreifen",
    "ch.swisstopo.lubis-luftbilder-dritte-firmen",
    "ch.swisstopo.lubis-luftbilder-dritte-kantone",
    "ch.swisstopo.lubis-luftbilder_farbe",
    "ch.swisstopo.lubis-luftbilder_infrarot",
    "ch.swisstopo.lubis-luftbilder_schraegaufnahmen",
    # "ch.swisstopo.lubis-luftbilder_schwarzweiss",
    "ch.swisstopo.lubis-terrestrische_aufnahmen",
    "ch.swisstopo.pixelkarte-pk100.metadata",
    "ch.swisstopo.pixelkarte-pk200.metadata",
    "ch.swisstopo.pixelkarte-pk25.metadata",
    "ch.swisstopo.pixelkarte-pk50.metadata",
    "ch.swisstopo.schneeschuhwandern",
    "ch.swisstopo.swissboundaries3d-bezirk-flaeche.fill",
    "ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill",
    # "ch.swisstopo.swissboundaries3d-kanton-flaeche.fill",
    # "ch.swisstopo.swissboundaries3d-land-flaeche.fill",
    "ch.swisstopo.swissimage-product.metadata",
    "ch.swisstopo.swissnames3d",
    "ch.swisstopo.swisssurface3d-raster.metadata",
    "ch.swisstopo.swisssurface3d.metadata",
    "ch.swisstopo.swisstlm3d-eisenbahnnetz",
    "ch.swisstopo.swisstlm3d-gewaessernetz",
    "ch.swisstopo.swisstlm3d-strassen",
    "ch.swisstopo.swisstlm3d-uebrigerverkehr",
    "ch.swisstopo.swisstne-base",
    "ch.swisstopo.transformation-bezugsrahmen_hoehe",
    "ch.swisstopo.transformationsgenauigkeit",
    "ch.swisstopo.vec200-adminboundaries-protectedarea",
    "ch.swisstopo.vec200-hydrography",
    "ch.swisstopo.vec200-landcover",
    "ch.swisstopo.vec200-miscellaneous",
    "ch.swisstopo.vec200-names-namedlocation",
    "ch.swisstopo.vec200-transportation-oeffentliche-verkehr",
    "ch.swisstopo.vec200-transportation-strassennetz",
    "ch.swisstopo.vec25-anlagen",
    "ch.swisstopo.vec25-einzelobjekte",
    "ch.swisstopo.vec25-gebaeude",
    "ch.swisstopo.vec25-gewaessernetz_referenz",
    "ch.swisstopo.vec25-heckenbaeume",
    "ch.swisstopo.vec25-primaerflaechen",
    "ch.swisstopo.verschiebungsvektoren-tsp1",
    "ch.swisstopo.verschiebungsvektoren-tsp2",
    "ch.swisstopo.zeitreihen",
    # "ch.vbs.armee-kriegsdenkmaeler",
    # "ch.vbs.armeelogistikcenter",
    # "ch.vbs.bundestankstellen-bebeco",
    "ch.vbs.kataster-belasteter-standorte-militaer",
    # "ch.vbs.logistikraeume-armeelogistikcenter",
    # "ch.vbs.panzerverschiebungsrouten",
    # "ch.vbs.patrouilledesglaciers-a_rennen",
    # "ch.vbs.patrouilledesglaciers-z_rennen",
    # "ch.vbs.retablierungsstellen",
    # "ch.vbs.sachplan-infrastruktur-militaer_anhoerung",
    # "ch.vbs.sachplan-infrastruktur-militaer_kraft",
    # "ch.vbs.schiessanzeigen",
    # "ch.vbs.territorialregionen",
    "ch.vbs.waldschadenkarte",
]

def pretty_print_json(json_data):
    ''' Pretty print a json object '''
    print(json.dumps(json_data, sort_keys=True, indent=1))


def pretty_print_json_in_textfile(json_data):
    ''' Pretty print a json object and write it to a text file '''

    with open("mydata.txt", "a") as file:
        file.write(f"Size: {len(json_data)}")  # Schreibe die Anzahl der JSON-Daten in die Datei
        json.dump(json_data, file, sort_keys=True, indent=1)
        file.write("\n")  # Füge eine Zeilenumbruch hinzu, um die JSON-Daten voneinander zu trennen


class DataFetcher:
    def __init__(self):
        pass

    async def _fetch_object_data(self,url,params=None):
        ''' Fetch data from the API '''
        async with httpx.AsyncClient() as client:
            try:
                response = await client.get(url, params=params)
                response.raise_for_status()
                response.json()
                return response.json()
            except httpx.RequestError as e:
                print(f"Error: {e}")
        return None

    async def search_addresses(self,search_text):
        ''' Search for addresses using the feature search service '''

        url = "https://api3.geo.admin.ch/rest/services/api/SearchServer"
        params = {
            "features": "ch.bfs.gebaeude_wohnungs_register",
            "type": "featuresearch",
            "searchText": search_text,
            "returnGeometry": "true",
        }
        addresses = await self._fetch_object_data(url,params)
        return addresses

    async def get_wohnungsregister(self, feature_id):
        ''' Get the wohnungsregister for a given feature id '''
        object_url = f"https://api3.geo.admin.ch/rest/services/api/MapServer/ch.bfs.gebaeude_wohnungs_register/{feature_id}"
        object_data = await self._fetch_object_data(object_url)
        return object_data

    async def get_from_different_layers_by_bbox(self,bbox,layer):
        ''' Get data from different layers'''
        geometry_param = ",".join(map(str, bbox))
        layers_param_all = "all:"+layer
            
        url = "https://api3.geo.admin.ch/rest/services/api/MapServer/identify"
        params = {
            "geometryType": "esriGeometryPoint",
            "geometry": geometry_param,
            "imageDisplay": "0,0,0",
            "mapExtent": "0,0,0,0",
            "tolerance": "0",
            "layers": layers_param_all,
            "returnGeometry": "false",
            }

        res = await self._fetch_object_data(url,params)
        return res

    def _if_extendedHtmlPopup_possible(self,url_string):
        ''' Checks if part of the url_string machts with an string in the currated_list and when yes, rename the part "htmlPopup" to "extendedHtmlPopup" in url_string. '''
        
        currated_list = ["ch.bfs.gebaeude_wohnungs_register",
                         "ch.bfs.gebaeude_wohnungs_register_waermequelle_heizung",]

        for currated_string in currated_list:
            if currated_string in url_string:
                new_url_string = url_string.replace("htmlPopup","extendedHtmlPopup")
                return new_url_string
            else:
                return url_string
        return None


    async def get_html_popup_layer_urls_by_bbox(self,bbox,layerlist=html_popup_layers):
        if layerlist == None:
            layerlist = html_popup_layers
        html_popup_layer_urls_for_bbox = []
        for layer in layerlist:
            try:
                layer_res_feature_id = await self.get_from_different_layers_by_bbox(bbox,layer)
               # if len(layer_res['results'])>0:
                url = f"https://api3.geo.admin.ch/rest/services/api/MapServer/{layer_res_feature_id['results'][0]['layerBodId']}/{layer_res_feature_id['results'][0]['featureId']}/htmlPopup?lang=de"
                html_popup_layer_urls_for_bbox.append(url)
            except:
                pass
  
        list_we_return = []
        for url in html_popup_layer_urls_for_bbox:
            list_we_return.append(self._if_extendedHtmlPopup_possible(url))
        return list_we_return

 
    async def get_html_popup_layer_urls_by_egid(self,egid,layerlist=html_popup_layers):
        if layerlist == None:
            layerlist = html_popup_layers
        print("searching for egid: " +egid[0])
        html_popup_layer_urls_for_egid = []
        
        for layer in layerlist:
            url_html = f"https://api3.geo.admin.ch/rest/services/api/MapServer/{layer}/{egid}/htmlPopup?lang=de"
            url_json = f"https://api3.geo.admin.ch/rest/services/api/MapServer/{layer}/{egid}"
            try:
                res = await self._fetch_object_data(url_json)
                print(url_json)
                html_popup_layer_urls_for_egid.append(url_html)
            except:
                pass
        for layer in layerlist:
            url_html = f"https://api3.geo.admin.ch/rest/services/api/MapServer/{layer}/{egid}_0/htmlPopup?lang=de"
            url_json = f"https://api3.geo.admin.ch/rest/services/api/MapServer/{layer}/{egid}_0"
            try:
                res = await self._fetch_object_data(url_json)
                print(url_json)
                html_popup_layer_urls_for_egid.append(url_html)
            except:
                pass

        list_we_return = []
        for url in html_popup_layer_urls_for_egid:
            list_we_return.append(self._if_extendedHtmlPopup_possible(url))
        return list_we_return





if __name__ == "__main__":
    api = DataFetcher()
   
    res = asyncio.run(api.search_addresses("Bundesplatz 1 Bern"))

    #print("\n\nAddresse:")
    #pretty_print_json(res)

    print("\n\nWohnungsregister:")
    feature_id = res['results'][0]['attrs']['featureId']
    wohnungsregister = asyncio.run(api.get_wohnungsregister(feature_id))
    pretty_print_json(wohnungsregister)

    print("\n\nbbox:")
    bbox = wohnungsregister['feature']['bbox']
    pretty_print_json(bbox)

    print("\n\negid:")
    egid = wohnungsregister['feature']['attributes']['egid']
    pretty_print_json(egid)

    layer_to_test = ["ch.babs.kulturgueter"]

    # print("\n\niframe urls by bbox:")
    # urls_to_iframe = asyncio.run(api.get_html_popup_layer_urls_by_bbox(bbox,layer_to_test))
    # pretty_print_json(urls_to_iframe)
    # pretty_print_json_in_textfile(urls_to_iframe)


    print("\n\niframe urls by egid:")
    urls_to_iframe = asyncio.run(api.get_html_popup_layer_urls_by_egid(egid,layer_to_test))
    pretty_print_json(urls_to_iframe)
    pretty_print_json_in_textfile(urls_to_iframe)

    # print("\n\All layer with results:")
    # for layer in html_popup_layers[0:10]:
    #     html_popup_layer_urls_for_bbox = []
    #     try:
    #         layer_res = asyncio.run(api.get_from_different_layers(bbox,layer))
    #         #print(f"len(layer_res['results']): {len(layer_res['results'])}, layer: {layer}                  ")
    #         #pretty_print_json(layer_res)
    #         #print("\n\n")
    #         if len(layer_res['results']):
    #             url = f"https://api3.geo.admin.ch/rest/services/api/MapServer/{layer_res['results'][0]['layerBodId']}/{layer_res['results'][0]['featureId']}/htmlPopup"
    #             html_popup_layer_urls_for_bbox.append(url)
    #             #print("'"+layer+"',")
    #             print(layer_res['results'][0]['layerBodId'])
    #             print(layer_res['results'][0]['featureId'])
    #     except:
    #         pass

    # print("\n\nSome layer with results:")
    # for layer in some_of_all_ch_layers[]:
    #     try:
    #         layer_res = asyncio.run(api.get_from_different_layers(bbox,layer))
    #         if len(layer_res['results'])>0:
    #             pretty_print_json_in_textfile(layer_res)
    #     except:
    #         pass



# https://api3.geo.admin.ch/rest/services/api/MapServer/ch.bfe.solarenergie-eignung-daecher/17060769/htmlPopup
# die feature id stammt 17060769  von layer_res = asyncio.run(api.get_from_different_layers(bbox,layer))
        
# dito: https://api3.geo.admin.ch/rest/services/api/MapServer/ch.are.bauzonen/390242/htmlPopup
        
# dito: https://api3.geo.admin.ch/rest/services/api/MapServer/ch.bag.radonkarte/18253/htmlPopup
        